server:
  port: 8081
spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        master:
          url: jdbc:mysql://47.106.139.187:3306/TravelFriend?serUnicode=true&characterEncoding=UTF8&useSSL=false
          username: root
          password: lxyLXY04/111997
          driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    #host: 127.0.0.1
    host: 123.56.6.43
    #host: 47.106.139.187
    port: 5672
    #username: guest
    #password: guest
    username: root
    password: root
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
  redis:
    host: localhost
    port: 6379
    #password: 123456
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
log:
  showToWeb : true
mysys:
  setting:
    master-node: true
login:
  cache:
    type: memory #redis or memory

logging:
  config: classpath:log4j2.xml