server:
  servlet:
    context-path:
  tomcat:
    max-http-form-post-size: -1
spring:
  profiles:
    active: test
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    dynamic:
      strict : true
      druid:
        initial-size: 0
        min-idle: 5
        max-active: 20
        max-wait: 10000
        killWhenSocketReadTimeout: true
        fail-fast : true
        time-between-eviction-runsMillis: 60000
        min-evictable-idle-timeMillis: 300000
        validation-query: select 'X' FROM DUAL
        test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
        use-global-data-source-stat: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:xml/*.xml
  global-config:
    id-type: 3
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
file:
  rootPath: /root/travelfriend
  sonPath: /user/image/avatar
  #rootPath: D:/
  #sonPath: image
  prefix: COMPRESS_