package com.sbzze.travelfriend.entity;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableId;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated
     */
    @TableId("id")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testString
     *
     * @mbggenerated
     */
    @NotNull(message = "传入的测试字符串为null，请传值")
    @NotEmpty(message = "传入的测试字符串为空，请传值")
    @TableField("testString")
    private String teststring;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    public Test(String id, String teststring) {
        this.id = id;
        this.teststring = teststring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    public Test() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testString
     *
     * @return the value of test.testString
     *
     * @mbggenerated
     */
    public String getTeststring() {
        return teststring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testString
     *
     * @param teststring the value for test.testString
     *
     * @mbggenerated
     */
    public void setTeststring(String teststring) {
        this.teststring = teststring == null ? null : teststring.trim();
    }
}